export const types = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    FETCH_SELF: 'FETCH_SELF',
    LOGOUT: 'LOGOUT',
    FORGOT: 'FORGOT',
    RECOVER: 'RECOVER'
};