export const types = {
    FETCH_COURSES: 'FETCH_COURSES',
    FETCH_COURSE: 'FETCH_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    CREATE_COURSE: 'CREATE_COURSE'
};