export const types = {
    FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
    CREATE_TRANSACTION: 'CREATE_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    VALIDATE_TRANSACTION: 'VALIDATE_TRANSACTION',
    DOWNLOAD_PROOF: 'DOWNLOAD_PROOF'
};